[clang-tidy-19] Enable readability-math-missing-parentheses
```
error: '*' has higher precedence than '-'; add parentheses to explicitly specify the order of operations
[readability-math-missing-parentheses,-warnings-as-errors]
```