[Storage] Use braces instead of parens in forwarding constructors
error: aggregate initialization of type 'X' from a parenthesized list
of values is a C++20 extension [-Werror,-Wc++20-extensions]